VIH-7520 add extra timing for the nsg rule

diff --git a/pipeline/stages/test.yaml b/pipeline/stages/test.yaml
--- a/pipeline/stages/test.yaml
+++ b/pipeline/stages/test.yaml
@@ -30,13 +30,12 @@ stages:
                 metricName="DipAvailability"
                 resourceType="Microsoft.Network/loadBalancers"
 
+                #wait for 2 rounds of the metrics to run before checking the probe
                 sleep 2m
-                healthResults=$(az monitor metrics list --resource $lbName --resource-group $rgName --resource-type $resourceType --metric $metricName --query "(value[0].timeseries[0].data)[*].average" -o tsv)
+                healthResults=$(az monitor metrics list --resource $lbName --resource-group $rgName --resource-type $resourceType --metric $metricName --query "(value[0].timeseries[0].data)[0:5].average" -o tsv)
                 echo $healthResults
 
                 healthSuccess=true
-                c=0
-                m=5
                 for i in $healthResults
                 do
                     val=`echo $i | sed 's/\\r//g'`
@@ -44,11 +43,6 @@ stages:
                     then
                         healthSuccess=false
                     fi
-                    if [ "$c" == "$m" ] 
-                    then
-                        break
-                    fi
-                    c=$((c+1))
                 done
 
                 if [ "$healthSuccess" = "false" ]
@@ -126,7 +120,37 @@ stages:
                 echo "Create NSG rule"
                 az network nsg rule create --name $ruleName --nsg-name $nsgName --priority '200' --resource-group $rgName --access 'Allow' --description "Test from the Deployment Pipeline"  --destination-port-ranges '443' --direction 'Inbound' --protocol 'Tcp' --source-address-prefixes $sourceIp  --source-port-ranges '*'
 
-                sleep 20s
+                # wait for rule to apply
+                ruleSet=false
+                for i in {1..3}
+                do
+                    nsgRuleId=$(az network nsg rule show --resource-group $rgName  --name $ruleName --nsg-name $nsgName --query "id" -o tsv)
+                    if [[ ! -z "$nsgRuleId" ]] 
+                    then
+                        ruleSet=true
+                        break
+                    fi
+                    echo "NSG Rule ${nsgRuleId} not found"
+                    sleep 20s
+                done
+
+                if [ "${ruleSet}" = "false" ]
+                then
+                    echo "##vso[task.LogIssue type=error;]Failed to set $ruleName in $nsgName"
+                    exit 1
+                fi
+
+                testCertificate(){
+                    echo "Test Cert on $1"
+                    if true | openssl s_client -connect "$1:443" 2>/dev/null | openssl x509 -noout -checkend 0; then
+                        echo "Certificate is not expired"
+                        return 1
+                    else
+                        echo "Certificate is expired"
+                        return 0
+                    fi
+                }
+
                 allOk=true
                 for i in {1..2}
                 do
@@ -135,7 +159,7 @@ stages:
                     echo "Testing $vmName in $rgName."
 
                     publicIpName="${service_name}pipvm${i}"
-                    publicIp="$(az network public-ip show -g ${rgName} -n ${publicIpName} --query "ipAddress" -o tsv)"
+                    publicIp=$(az network public-ip show -g ${rgName} -n ${publicIpName} --query "ipAddress" -o tsv)
 
                     echo "Test Cert on $publicIp"
                     if true | openssl s_client -connect "$publicIp:443" 2>/dev/null | openssl x509 -noout -checkend 0; then
