VIH-8038 Add wowza service checking

diff --git a/pipeline/stages/test.yaml b/pipeline/stages/test.yaml
--- a/pipeline/stages/test.yaml
+++ b/pipeline/stages/test.yaml
@@ -87,7 +87,7 @@ stages:
 
                     vmName="${service_name}vm${i}"
                     echo "Testing $vmName in $rgName."
-                    
+
                     response=$(az vm run-command invoke --resource-group $rgName --name $vmName --command-id RunShellScript --scripts '[ -d "/usr/local/WowzaStreamingEngine/content/azurecopy" ] && echo "Directory exists." || echo "Error: Directory does not exists."' --query "value[0].message")
 
                     if [[ $response == *"Directory exists"* ]]; then
@@ -104,7 +104,41 @@ stages:
                     echo "##vso[task.LogIssue type=error;]There are issues with vms in $rgName"
                     exit 1
                 fi
-          
+          - task: AzureCLI@2
+            name: 'wowzaservice'
+            displayName: Check Wowza Service
+            inputs:
+              azureSubscription: '${{variables.subscriptionName}}'
+              scriptType: 'bash'
+              scriptLocation: 'inlineScript'
+              inlineScript: |
+                service_name="${{variables.product}}-recordings-${{parameters.env}}-"
+                rgName="${service_name}rg"
+
+                allOk=true
+                for i in {1..2}
+                do
+
+                    vmName="${service_name}vm${i}"
+                    echo "Testing $vmName in $rgName."
+
+                    response=$(az vm run-command invoke --resource-group $rgName --name $vmName --command-id RunShellScript --scripts 'systemctl is-active --quiet WowzaStreamingEngine && echo "Service Running" || echo "Error: Service not Running"' --query "value[0].message")
+
+                    if [[ $response == *"Service Running"* ]]; then
+                      echo "It's there!"
+                    else
+                      echo "##vso[task.LogIssue type=error;]The Wowza Service is not running in $vmName in $rgName"
+                      allOk=false
+                    fi
+
+                done
+
+                if [ "$allOk" = "false" ]
+                then
+                    echo "##vso[task.LogIssue type=error;]There are issues with vms in $rgName"
+                    exit 1
+                fi
+                
 #          - template: templates\tests\Azure\VirtualMachine\validSslCertificate.yml@azTemplates
 #            parameters:
 #              subscriptionName: ${{variables.subscriptionName}}
