updating VM tests to allow dynamic VM count

diff --git a/pipeline/stages/test.yaml b/pipeline/stages/test.yaml
--- a/pipeline/stages/test.yaml
+++ b/pipeline/stages/test.yaml
@@ -60,91 +60,97 @@ stages:
 
                   Write-Output "Task finished: getvmnames"
 
-            - ${{ each vm in split(getvmnames.vmNames, ',') }}:
-              - task: AzureCLI@2
-                name: 'machineconfig'
-                displayName: Check Machine Config - $vm
-                inputs:
-                  azureSubscription: '${{variables.subscriptionName}}'
-                  scriptType: 'bash'
-                  scriptLocation: 'inlineScript'
-                  inlineScript: |
-                    service_name="${{variables.product}}-recordings-${{parameters.env}}-"
-                    rgName="${service_name}rg"
-                    vmName="${vm}"
+            - task: AzureCLI@2
+              name: 'machineconfig'
+              displayName: Check Machine Config - $vm
+              inputs:
+                azureSubscription: '${{variables.subscriptionName}}'
+                scriptType: 'bash'
+                scriptLocation: 'inlineScript'
+                inlineScript: |
+                  rgName="${service_name}rg"
+                  allOk=true
+                  IFS=';' read -ra vms <<< "${getvmnames.vmListString}"
+                  for i in "${vms[@]}"
+                  do
 
-                    allOk=true
+                      vmName="${i}"
+                      echo "Testing $vmName in $rgName."
 
-                    echo "Testing $vmName in $rgName."
+                      #az vm show --resource-group $rgName --name $vmName
+                      passwordDisabled=$(az vm show --resource-group $rgName --name $vmName --query "osProfile.linuxConfiguration.disablePasswordAuthentication" -o tsv)
+                      if [ "$passwordDisabled" = "false" ]
+                      then
+                          echo "##vso[task.LogIssue type=error;]$vmName in $rgName has password access enabled."
+                          allOk=false
+                      fi
+                  
+                  done
 
-                    #az vm show --resource-group $rgName --name $vmName
-                    passwordDisabled=$(az vm show --resource-group $rgName --name $vmName --query "osProfile.linuxConfiguration.disablePasswordAuthentication" -o tsv)
-                    if [ "$passwordDisabled" = "false" ]
-                    then
-                        echo "##vso[task.LogIssue type=error;]$vmName in $rgName has password access enabled."
-                        allOk=false
-                    fi
-                        
-                    if [ "$allOk" = "false" ]
-                    then
-                        echo "##vso[task.LogIssue type=error;]There are issues with vms in $rgName"
-                        exit 1
-                    fi
-            - ${{ each vm in split(getvmnames.vmNames, ',') }}:
-              - task: AzureCLI@2
-                name: 'vminstalls'
-                displayName: Check VM Installs
-                inputs:
-                  azureSubscription: '${{variables.subscriptionName}}'
-                  scriptType: 'bash'
-                  scriptLocation: 'inlineScript'
-                  inlineScript: |
-                    service_name="${{variables.product}}-recordings-${{parameters.env}}-"
-                    rgName="${service_name}rg"
-                    vmName="${vm}"
+                  if [ "$allOk" = "false" ]
+                  then
+                      echo "##vso[task.LogIssue type=error;]There are issues with vms in $rgName"
+                      exit 1
+                  fi
 
-                    allOk=true
+            - task: AzureCLI@2
+              name: 'vminstalls'
+              displayName: Check VM Installs
+              inputs:
+                azureSubscription: '${{variables.subscriptionName}}'
+                scriptType: 'bash'
+                scriptLocation: 'inlineScript'
+                inlineScript: |
+                  rgName="${service_name}rg"
+                  allOk=true
+                  IFS=';' read -ra vms <<< "${getvmnames.vmListString}"
+                  for i in "${vms[@]}"
+                  do
 
-                    echo "Testing $vmName in $rgName."
+                      vmName="${i}"
+                      echo "Testing $vmName in $rgName."
 
-                    response=$(az vm run-command invoke --resource-group $rgName --name $vmName --command-id RunShellScript --scripts '[ -d "/usr/local/WowzaStreamingEngine/content/azurecopy" ] && echo "Directory exists." || echo "Error: Directory does not exists." && dpkg -s fuse |grep "install ok installed" && echo "fuse pgk installed" || echo "fuse pgk failed" && dpkg -s blobfuse |grep "install ok installed" && echo "blobfuse installed" || echo "blobfuse failed" && systemctl is-active --quiet WowzaStreamingEngine && echo "Service Running" || echo "Error: Service not Running"' --query "value[0].message")
+                      response=$(az vm run-command invoke --resource-group $rgName --name $vmName --command-id RunShellScript --scripts '[ -d "/usr/local/WowzaStreamingEngine/content/azurecopy" ] && echo "Directory exists." || echo "Error: Directory does not exists." && dpkg -s fuse |grep "install ok installed" && echo "fuse pgk installed" || echo "fuse pgk failed" && dpkg -s blobfuse |grep "install ok installed" && echo "blobfuse installed" || echo "blobfuse failed" && systemctl is-active --quiet WowzaStreamingEngine && echo "Service Running" || echo "Error: Service not Running"' --query "value[0].message")
 
-                    echo "$response"
-                    echo ""
+                      echo "$response"
+                      echo ""
 
-                    if [[ $response == *"fuse pgk installed"* ]]; then
-                        echo "The fuse package installed on $vmName in $rgName"
-                    else
-                        echo "##vso[task.LogIssue type=error;]The fuse package failed to install on $vmName in $rgName"
-                        allOk=false
-                    fi
+                      if [[ $response == *"fuse pgk installed"* ]]; then
+                          echo "The fuse package installed on $vmName in $rgName"
+                      else
+                          echo "##vso[task.LogIssue type=error;]The fuse package failed to install on $vmName in $rgName"
+                          allOk=false
+                      fi
 
-                    if [[ $response == *"blobfuse installed"* ]]; then
-                        echo "The blobfuse package installed on $vmName in $rgName"
-                    else
-                        echo "##vso[task.LogIssue type=error;]The blobfuse package failed to install on $vmName in $rgName"
-                        allOk=false
-                    fi
+                      if [[ $response == *"blobfuse installed"* ]]; then
+                          echo "The blobfuse package installed on $vmName in $rgName"
+                      else
+                          echo "##vso[task.LogIssue type=error;]The blobfuse package failed to install on $vmName in $rgName"
+                          allOk=false
+                      fi
 
-                    if [[ $response == *"Service Running"* ]]; then
-                        echo "The Wowza Service is running in $vmName in $rgName"
-                    else
-                        echo "##vso[task.LogIssue type=error;]The Wowza Service is not running in $vmName in $rgName"
-                        allOk=false
-                    fi
+                      if [[ $response == *"Service Running"* ]]; then
+                          echo "The Wowza Service is running in $vmName in $rgName"
+                      else
+                          echo "##vso[task.LogIssue type=error;]The Wowza Service is not running in $vmName in $rgName"
+                          allOk=false
+                      fi
 
-                    if [[ $response == *"Directory exists"* ]]; then
-                        echo "The blob storage is attached to $vmName in $rgName"
-                    else
-                        echo "##vso[task.LogIssue type=error;]The blob storage is not attached to $vmName in $rgName"
-                        allOk=false
-                    fi
+                      if [[ $response == *"Directory exists"* ]]; then
+                          echo "The blob storage is attached to $vmName in $rgName"
+                      else
+                          echo "##vso[task.LogIssue type=error;]The blob storage is not attached to $vmName in $rgName"
+                          allOk=false
+                      fi
 
-                    if [ "$allOk" = "false" ]
-                    then
-                        echo "##vso[task.LogIssue type=error;]There are issues with vms in $rgName"
-                        exit 1
-                    fi
+
+                  done
+
+                  if [ "$allOk" = "false" ]
+                  then
+                      echo "##vso[task.LogIssue type=error;]There are issues with vms in $rgName"
+                      exit 1
+                  fi
 
             - ${{ if ne(parameters.env, 'sbox') }}:
               - template: ..\steps\test-ffmpeg.yml
